# import required libraries
from pathlib import Path
from os.path import join as pjoin
import pandas as pd

# read the configuration file
configfile: "../conf/config_finemap.yaml"


include: "rules/common.smk"


rule all:
    input:
        expand(ws_path("logs/cojo/{seqid}.log"), seqid=analytes.seqid),
        #expand(ws_path("output/break/{seqid}_loci.csv"), seqid=analytes.seqid)


#rule break_locus:
#    input:
#        gwas = ss_path("{seqid}.gwas.regenie.gz")
#    output:
#        loci = ws_path("output/break/{seqid}_loci.tsv"),
#    params:
#        codes = config.get("path_code"),
#        ifile = ss_path("{seqid}"),
#        ofile = ws_path("output/break/{seqid}"),
#        seque = "{seqid}",
#        p1    = config.get('thresholds').get('p1'),
#        p2    = config.get('thresholds').get('p2'),
#        hole  = config.get('thresholds').get('hole')
#    log:
#        ws_path("logs/break/{seqid}.log")
#    resources:
#        mem_mb = 8000, runtime = 60
#    shell:
#        """
#        source ~/.bashrc && \
#        conda activate r_finemap &&  \
#        Rscript scripts/s03_locus_breaker.R  \
#            --pipeline_path {params.codes}  \
#            --input {input.gwas}  \
#            --study_id  {params.ofile}  \
#            --p_thresh1 {params.p1}  \
#            --p_thresh2 {params.p2}  \
#            --hole   {params.hole} \
#            --outdir {params.ofile}  2> {log}
#        """


rule run_cojo:
    input:
        #gwas = ss_path("{seqid}.gwas.regenie.gz"), #.gwaslab.tsv.gz
        gwas = get_sumstats,
        loci = sc_path("{seqid}_loci.tsv")
    output:
        odir = directory(ws_path("output/cojo/{seqid}/")),
        log  = ws_path("logs/cojo/{seqid}.log")
    params:
        codes = config.get("path_code"),
        geno  = config.get("path_geno"),
        mapping = config.get("path_mapping"),
        ofile = ws_path("output/cojo/{seqid}/{seqid}"),
        ppp   = config.get('thresholds').get('ppp'),
        p3    = config.get('thresholds').get('p3'),
        p4    = config.get('thresholds').get('p4'),
        maf   = config.get('thresholds').get('maf')
    log:
        ws_path("logs/cojo/{seqid}.log")
    resources:
        mem_mb = 16000, runtime = 60
    run:
        # read the loci and loop over each locus
        with open(input.loci) as f:
            next(f)  # Skip the header row
            for line in f:
                chr, beg, end = line.strip().split('\t')[:3]
                shell("""
                source ~/.bashrc && \
                conda activate r_finemap &&  \
                Rscript scripts/s04_cojo_finemapping.R  \
                --pipeline_path   {params.codes}  \
                --dataset_aligned {input.gwas}  \
                --mapping  {params.mapping}  \
                --study_id {params.ofile}  \
                --chr   {chr}  \
                --start {beg}  \
                --end   {end}  \
                --bfile {params.geno} \
                --cs_thresh {params.ppp}  \
                --p_thresh3 {params.p3}  \
                --p_thresh4 {params.p4}  \
                --maf       {params.maf}  \
                --outdir {output.odir} \
                --phenotype_id full  \
                --nf_hcoloc_v no_nf  2>> {log}
                """
                )
