
path_loci: "/scratch/dariush.ghasemi/projects/pqtl_pipeline_finemap/results/meta/break"
#path_pwas: "/exchange/healthds/pQTL/results/INTERVAL_OLD/harmonized_sumstats/outputs"
#path_intv: "/exchange/healthds/pQTL/results/INTERVAL/chunk_6843/chunk_6843_output/chunk_6843/results/gwas"
#path_meta: "/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits/output/"
path_geno: "/scratch/dariush.ghasemi/genotype/imputed/plinkFormat/impute_recoded_selected_sample_filter_hq_var_chr"
path_mapping: "/exchange/healthds/pQTL/results/INTERVAL/qced_sumstats/table.snp_mapping.tsv.gz"

path_code: "scripts/"
path_workspace: "output/"
path_sumstats: "../conf/path_plots.txt"

#sample_seqids: ["7930.3", "13124.20", "7935.26", "7943.16", "19819.7", "5124.69", "12708.91", "12730.3", "13615.60"]


thresholds:
  p1: 5e-08
  p2: 1e-06
  p3: 1e-04
  p4: 1e-06
  maf: 1e-04
  ppp: 0.99
  hole: 250000