path_base: "/home/dariush.ghasemi/projects/pqtl_pipeline_finemap"
path_code: "/home/dariush.ghasemi/projects/pqtl_pipeline_finemap/workflow/scripts/"
path_pwas: "/exchange/healthds/pQTL/results/INTERVAL_OLD/harmonized_sumstats/outputs"
#sample_seqids: ["7930.3", "13124.20", "7935.26", "7943.16", "19819.7", "5124.69"]
sample_seqids: ["13124.20"]