path_base: "/home/dariush.ghasemi/projects/pqtl_pipeline_finemap"
path_code: "/home/dariush.ghasemi/projects/pqtl_pipeline_finemap/workflow/scripts/"
#path_pwas: "/exchange/healthds/pQTL/results/INTERVAL_OLD/harmonized_sumstats/outputs"
path_pwas: "/exchange/healthds/pQTL/results/INTERVAL/chunk_1083/chunk_1083_output/chunk_1083/results/gwas"
path_geno: "/home/dariush.ghasemi/projects/pqtl_pipeline_ldsc/output/plinkFormat/impute_recoded_selected_sample_filter_hq_var_chr"
#sample_seqids: ["7930.3", "13124.20", "7935.26", "7943.16", "19819.7", "5124.69"]
sample_seqids: ["13615.60"] #"12708.91", "12730.3"

thresholds:
  p1: 5e-08
  p2: 1e-06
  p3: 1e-04
  p4: 1e-06
  maf: 1e-04
  ppp: 0.99
  hole: 250000