path_code: "workflow/scripts/"
path_geno: "/scratch/giulia.pontali/genomics_QC_pipeline/results_scratch/bed/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"

sumstats_path: conf/path_meta_all.txt
workspace_path: "results/meta_digits"

labels:
  chr_label: "'#CHR'"
  pos_label: "POS"
  snpid_label: "SNPID"
  key_label: "PREVIOUS_ID"
  ea_label: "EA"
  oa_label: "NEA"
  eaf_label: "EAF"
  beta_label: "BETA"
  se_label: "SE"
  p_label: "MLOG10P"
  n_label: "N"

thresholds:
  p1: 1.256913021618904e-11
  p2: 1e-06
  p3: 1.256913021618904e-11
  p4: 1e-06
  maf: 1e-04
  ppp: 0.99
  hole: 250000
