executor: slurm
jobs: 250
software-deployment-method:
   - conda
   - apptainer
retries: 0

# Cluster submission
jobname: "{jobid}.{rule}"
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 2
latency-wait: 60
keep-going: True
rerun-incomplete: False
printshellcmds: True
scheduler: ilp

default-resources:
    slurm_partition: cpuq
    #slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5

set-resources:
    break_locus:
        mem_mb: 8000 + attempt * 2048
